version: '2'

services:
    web:
        image: nginx:1.11.4-alpine
        ports:
            - "8080:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        image: php:7.0.11-fpm-alpine
        volumes:
            - ./code:/code
        networks:
            - code-network
         
    db:
        image: mariadb:latest
        volumes:
            - ./data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=@dm9svr1
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
